FROM registry.svc.ci.openshift.org/ocp/builder:rhel-8-golang-openshift-4.6 AS builder
WORKDIR /go/src/github.com/openshift/bond-cni
COPY . .
RUN ./build.sh

FROM registry.svc.ci.openshift.org/ocp/4.6:base
LABEL io.k8s.display-name="bond-cni" \
    io.k8s.description="This is an image containing the bond-cni executable" \
    io.openshift.tags="openshift"

COPY --from=builder /go/src/github.com/openshift/bond-cni/bin/bond /bondcni/bond
