# URGENT! ART metadata configuration has a different number of FROMs
# than this Dockerfile. ART will be unable to build your component or
# reconcile this Dockerfile until that disparity is addressed.
FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.26-openshift-5.0 AS rhel9
WORKDIR /go/src/github.com/openshift/bond-cni
COPY . .
RUN go build --mod=vendor -ldflags '-s -w' -o ./bin/bond ./bond/

FROM registry.ci.openshift.org/ocp/5.0:base-rhel9
LABEL io.k8s.display-name="bond-cni" \
    io.k8s.description="This is an image containing the bond-cni executable" \
    io.openshift.tags="openshift"

COPY --from=rhel9 /go/src/github.com/openshift/bond-cni/bin/bond /bondcni/bond
